# Render Blueprint for GPG Webservice Suite
# ==========================================
# This file defines the infrastructure for deploying all three services:
# - gpg-webservice-rest (Flask REST API)
# - gpg-webservice-mcp (MCP Server)
# - gpg-webservice-dashboard (Nginx Static Dashboard)
#
# Deploy: Connect this repo to Render as a Blueprint
# Docs: https://render.com/docs/blueprint-spec

services:
  # =============================================================================
  # Flask REST API (Core Service)
  # =============================================================================
  - type: web
    name: gpg-webservice-rest
    runtime: docker
    dockerfilePath: ./gpg-webservice-rest/Dockerfile
    dockerContext: ./gpg-webservice-rest
    plan: free  # or: starter, standard, pro
    region: oregon  # or your preferred region
    branch: main
    
    # Render sets PORT automatically; service listens on this port
    envVars:
      - key: PORT
        value: 5555
      - key: HOST
        value: 0.0.0.0
      - key: FLASK_ENV
        value: production
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      
      # CRITICAL SECRETS - Set these in Render Dashboard as Secret Files or Environment Variables
      # DO NOT commit these to GitHub!
      - key: SERVICE_KEY_PASSPHRASE
        sync: false  # Must be set manually in Render dashboard
      - key: SECRET_KEY
        sync: false  # Must be set manually in Render dashboard
      
      # Admin access control
      - key: ADMIN_USERNAMES
        sync: false  # e.g., "administrator,alice,bob"
      - key: ADMIN_GPG_KEYS
        sync: false  # JSON string with admin GPG keys
      
      # Database (SQLite default; override with PostgreSQL in dashboard)
      - key: DATABASE
        value: /app/gpg_users.db
      
      # Rate limiting
      - key: RATE_LIMIT_AUTH_REQUESTS
        value: 5
      - key: RATE_LIMIT_AUTH_WINDOW
        value: 60
      - key: RATE_LIMIT_API_REQUESTS
        value: 30
      - key: RATE_LIMIT_API_WINDOW
        value: 60
      
      # File uploads
      - key: MAX_FILE_SIZE_MB
        value: 10
      - key: MAX_SIGNATURE_SIZE_MB
        value: 1
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      
      # GPG settings
      - key: GPG_KEY_LENGTH
        value: 3072
      - key: GPG_KEY_TYPE
        value: RSA
    
    # Persistent disk for SQLite database
    disk:
      name: gpg-data
      mountPath: /app
      sizeGB: 1
    
    healthCheckPath: /openai/function_definitions
    
    autoDeploy: true

  # =============================================================================
  # MCP Server (AI Agent Interface)
  # =============================================================================
  - type: web
    name: gpg-webservice-mcp
    runtime: docker
    dockerfilePath: ./gpg-webservice-mcp/Dockerfile
    dockerContext: ./gpg-webservice-mcp
    plan: free
    region: oregon
    branch: main
    
    envVars:
      - key: MCP_PORT
        value: 3000
      - key: MCP_HOST
        value: 0.0.0.0
      
      # Connect to REST API (update after REST service is deployed)
      # Format: https://gpg-webservice-rest.onrender.com
      - key: GPG_API_BASE
        sync: false  # Set this manually after REST service is deployed
      
      # Optional: API key for authenticated requests to REST
      - key: GPG_API_KEY
        sync: false
    
    healthCheckPath: /health
    
    autoDeploy: true

  # =============================================================================
  # Dashboard (Static Web UI)
  # =============================================================================
  - type: web
    name: gpg-webservice-dashboard
    runtime: docker
    dockerfilePath: ./gpg-webservice-dashboard/Dockerfile
    dockerContext: ./gpg-webservice-dashboard
    plan: free
    region: oregon
    branch: main
    
    envVars:
      # API endpoint for dashboard to connect to REST service
      # Update after REST service is deployed
      - key: API_URL
        sync: false  # Set to https://gpg-webservice-rest.onrender.com
    
    # Nginx listens on port 80 inside container; Render proxies this
    # No healthCheckPath needed (static files always available)
    
    autoDeploy: true

# =============================================================================
# DEPLOYMENT INSTRUCTIONS
# =============================================================================
#
# 1. BEFORE DEPLOYING:
#    - Push this render.yaml to your GitHub repository
#    - DO NOT commit secrets (SERVICE_KEY_PASSPHRASE, SECRET_KEY, etc.)
#
# 2. INITIAL DEPLOYMENT:
#    a. Go to Render Dashboard: https://dashboard.render.com/
#    b. Click "New" → "Blueprint"
#    c. Connect your GitHub repository
#    d. Render will detect this render.yaml and show you the three services
#    e. Click "Apply" to create all services
#
# 3. SET REQUIRED SECRETS (in Render Dashboard):
#    
#    For gpg-webservice-rest:
#    - SERVICE_KEY_PASSPHRASE: Generate with `openssl rand -base64 32`
#    - SECRET_KEY: Generate with `openssl rand -hex 32`
#    - ADMIN_USERNAMES: Comma-separated list (e.g., "administrator,alice")
#    - ADMIN_GPG_KEYS: JSON string (see .env.example for format)
#
#    For gpg-webservice-mcp:
#    - GPG_API_BASE: Set to your REST service URL (e.g., https://gpg-webservice-rest.onrender.com)
#    - GPG_API_KEY: (Optional) API key for authenticated requests
#
#    For gpg-webservice-dashboard:
#    - API_URL: Set to your REST service URL (same as GPG_API_BASE)
#
# 4. VERIFY DEPLOYMENT:
#    - REST API: https://gpg-webservice-rest.onrender.com/
#    - MCP Server: https://gpg-webservice-mcp.onrender.com/health
#    - Dashboard: https://gpg-webservice-dashboard.onrender.com/
#
# 5. IMPORTANT NOTES:
#    - Render automatically handles HTTPS (TLS termination at edge)
#    - Services detect RENDER environment variable and skip local TLS
#    - Free tier services sleep after inactivity; first request may be slow
#    - Consider upgrading to paid plans for production use
#    - For PostgreSQL: Add a database in Render and update DATABASE env var
#
# =============================================================================
